import sys,json,time
sys.path.insert(0,'/Users/alice/Hand')
from hand.perception.cdp_core import cdp_connect, cdp_call
from hand.router import route_open, route_do, route_see
pages = cdp_call(None, 'list')
page_ws = pages[0]['webSocketDebuggerUrl']
ws = cdp_connect(page_ws)
cdp_call(ws, 'Page.enable')
cdp_call(ws, 'Page.navigate', {'url': 'https://example.com'})
time.sleep(0.5)
print('INJECT:', cdp_call(ws, 'Runtime.evaluate', {'expression': 'document.body.innerHTML += "<div style=padding:20px;background:#f0f0f0;border-radius:8px><h2>Test Search</h2><input id=srch type=text placeholder=Search... style=padding:8px;width:300px;font-size:16px><button id=btn onclick=document.getElementById('res').innerText=document.getElementById('srch').value>Search</button><p id=res style=margin-top:16px;font-size:18px></p></div>"'}).get('result',{}).get('value'))
time.sleep(0.3)
print()
print('--- route_open ---')
print(json.dumps(route_open('https://example.com'), indent=2))
print()
print('--- route_do type ---')
r = route_do('type #srch|Hello World')
print(json.dumps(r, indent=2))
print()
v = cdp_call(ws, 'Runtime.evaluate', {'expression': 'document.getElementById(srch).value'})
print('VALUE:', v.get('result',{}).get('value'))
print()
print('--- route_do click ---')
print(json.dumps(route_do('click text=Search'), indent=2))
print()
v2 = cdp_call(ws, 'Runtime.evaluate', {'expression': 'document.getElementById(res).innerText'})
print('RESULT TEXT:', v2.get('result',{}).get('value'))
ws.close()
print('DONE')
